dist: xenial
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy2.7-6.0"
  - "pypy3.5-6.0"
install:
  - pip install coveralls
before_script:
  - pip install flake8
  - flake8
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
script:
  - coverage run --source=html2text setup.py test
  - coverage combine
  - coverage report
after_success:
    coveralls
