language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "pypy3"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  # Python 3.2 needs setuptools < 30 - support for Py3.2 was dropped after that version
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' || $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then pip install -U 'setuptools<30'; fi
install:
    - pip install coveralls==0.5
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  # flake8 doesn't support Python 2.6
  - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then pip install flake8==3.3.0;flake8 .; fi
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
script:
  - PYTHONPATH=$PYTHONPATH:. coverage run --source=html2text --rcfile=.coveragerc setup.py test -v
  - coverage combine
  - coverage report
after_success:
    coveralls --rcfile=.coveragerc
