language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
    - pip install coveralls==0.5
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - export COVERAGE_PROCESS_START=$PWD/.coveragerc
script:
  - PYTHONPATH=$PYTHONPATH:. coverage run --source=html2text --rcfile=.coveragerc setup.py test -v
  - coverage combine
  - coverage report
after_success:
    coveralls --rcfile=.coveragerc
