name: Publish to PyPI

on:
  release:
    types: [released]

jobs:
  release:
    name: Release
    environment:
      name: pypi
      url: https://pypi.org/project/html2text
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build
        run: |
          python -m pip install build
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
